version: "3.9"

services:
  nodeapp:
    image: node:lts
    container_name: nodeapp
    working_dir: /usr/src/app
    # No Dockerfiles are needed!
    ports:
      - "8080:8080" # node server http port
      - "9229:9229" # node inspect debug port
    networks:
      - app-network
    restart: on-failure
    command: npm run debug
    volumes:
      - ./app:/usr/src/app

networks:
  app-network:
    driver: bridge
# Docs here : https://github.com/compose-spec/compose-spec/blob/master/spec.md
