version: "3.9"

services:
  nodeapp:
    container_name: nodeapp
    build:
      context: ./app
      dockerfile: ./dev.Dockerfile # Dockerfile da pasta app
    ports:
      - "8080:8080" # node server http port
      - "9229:9229" # node inspect debug port
    networks:
      - app-network
    restart: on-failure
    volumes:
      - ./app:/usr/src/app # gain a nodemon support

networks:
  app-network:
    driver: bridge
# Docs here : https://github.com/compose-spec/compose-spec/blob/master/spec.md
