version: "3.9"

services:
  nodeapp:
    container_name: nodeapp
    build:
      context: ./app
      dockerfile: ../Dockerfile # Dockerfile fora da pasta app
    ports:
      - "8080:8080" # node server http port
      - "9229:9229" # node inspect debug port
    networks:
      - app-network
    restart: on-failure
    command: npm run debug
    # volumes: producao não se usa volumes locais
    # Nao usar inspect com brk, use apenas assim {nodemon --inspect=0.0.0.0:9229}
    # sem volumes mapeados não temos diretamente as funcionalidades do nodemon como restart on changes.

networks:
  app-network:
    driver: bridge
# Docs here : https://github.com/compose-spec/compose-spec/blob/master/spec.md
