version: "3.9"

services:
  nodeapp:
    container_name: nodeapp
    build:
      context: ../app
      dockerfile: ../config-prod/Dockerfile # Dockerfile in relation to the app folder
    ports:
      - "8080:8080" # node server http port
      - "9229:9229" # node inspect debug port
    networks:
      - app-network
    restart: on-failure
    command: npm run debug
    # volumes: production does not need to use local volumes
    # In package-json use with or without -brk, so {nodemon --inspect=0.0.0.0:9229}
    # However, without volumes mapped here, we will not have nodemon features like restart on changes.

networks:
  app-network:
    driver: bridge
# Docs here : https://github.com/compose-spec/compose-spec/blob/master/spec.md
